### ISSUE TITLE
Procedura: incarcare cod

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/docs#17]
```
Versiunea proiectului din data de 27 Iulie va fi versiunea proiectului ce va fi prezentată în cadrul concursului.
Fiecare echipă are datoria de a pune la dispoziția juriului toate resursele necesare jurizării până la această dată.
```

Trebuie pusa o prima versiune pe GitHub pana pe 30 si poate fi actualizat pana cand incep instalarile.

**Comment by vtemian** [comment]
Militez pentru 1 august

**Comment by alexcoman** [comment]
Propun următoarea abordare:

| Data | Termen limită pentru |
| --- | --- |
| 27 Iulie | înscrierea proiectului |
| 1 August | modificări ale codului ce vor fi jurizate |

Pentru a evita probleme, cel mai ok este să facem acest lucru înainte de începerea taberei.

Juriul poate decide să ia în considerare modificări ulterioare, dar nu vor fi punctate.

Are legătură cu #21
