### ISSUE TITLE
Procedura: folosire hardware propriu

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/docs#19]
```
În cazul în care o echipă nu poate instala proiectul pe infrastuctura pusă la dispoziție de membrii comisiei tehnice din motive întemeiate aceasta poate prezenta proiectul de pe hardware-ul propriu.
```

Trebuie spus clar ca au nevoie de aprobarea comisiei pt asta si ca nu decid ei ce e intemeiat si ce nu. De ex: daca e scris prost nu e chiar intemeiat

**Comment by alexcoman** [comment]
Ok, atunci o să adăugăm o serie de articole care să explice acest aspect.
