### ISSUE TITLE
Procedura: resurse relevante

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/docs#22]
```
În cazul în care o parte dintre resursele relevante lipsesc, membrii comisiei nu vor puncta proiectul în cauză.
```

Ce inseamna resursa relevanta? Cum decizi ca lipseste o resursa relevanta ca sa nu ii punctezi?

**Comment by alexcoman** [comment]
Multe dintre aceste informații ar trebui specificate în criteriile de jurizare.

Cred că cel mai ok ar fi ca fiecare comisie să decidă ce înseamnă resurse relevante pentru proiectele de la secțiunea respectivă.

Putem totuși să le agregăm în proceduri specificând diferențele dintre secțiuni.

**Comment by robertdxyz** [comment]
Nu imi place pentru ca ce scrie acum e ca daca nu faceti cum vrem noi va dam afara si nu e deloc ok sa nu fie clar unde gasesc ce trebuie sa faca.

Plus, eu as merge pe depunctare.

**Comment by alexcoman** [comment]
Și cu cât depunctezi o echipă care nu ți-a dat codul sursă ?
