### ISSUE TITLE
Procedura: afisare punctaje

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/docs#23]
```
Punctajele pentru primele cinci echipe clasate, la fiecare secțiune, nu vor fi afișate.
```

Nu se afiseaza niciun punctaj, nici la cei care sunt sub locul 5. Toate punctajele/clasamentele se afla la premiere.

**Comment by alexcoman** [comment]
Nu țin minte să se făcut asta până acum.

Din câte țin eu minte nu se afișau punctajele doar pentru cei care au intrat în Open.

**Comment by robertdxyz** [comment]
Pot sa iti spun ca nu ti minte bine :)

**Comment by alexcoman** [comment]
Nu se afișa premiul pentru proiectele de sub locul 5, dar punctajele se afișau.

**Comment by robertdxyz** [comment]
Nu :) In ultimii 2 ani sigur nu pentru ca am insistat eu sa nu se faca asta. Iti garantez
