### ISSUE TITLE
Procedura: calificare open

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/docs#24]
```
Primele cinci echipe de la fiecare secțiune se vor califica în proba "Open".
```

Ce se intampla daca exista egalitate la punctaje?

**Comment by alexcoman** [comment]
De asemenea ce se întâmplă în situația în care o echipă se califică cu două proiecte la proba **Open** ?

**Comment by robertdxyz** [comment]
Alege unul doar

**Comment by alexcoman** [comment]
Nu mi se pare corect.

**Comment by robertdxyz** [comment]
Dar cum ti se pare corect. Propune ceva daca nu e bine asa.
